version: "3"

services:
  database:
    image: postgres:alpine
    env_file: .env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    ports:
      - "8080:8080"
    links:
      - database

volumes:
  db: